export const ANIMATION_DELAYS = {
  HOURGLASS_TASK: 1500,
  NORMAL_TASK: 1000,
  QUICK_TASK: 500,
} as const

export const ANIMATION_THRESHOLDS = {
  RETRY_THRESHOLD: 10,
  RECOVERY_START_INDEX: 8,
  ERROR_RECOVERY_STEP_LIMIT: 10,
} as const
