export {
  postgresqlOperationDeparser,
  postgresqlSchemaDeparser,
} from './deparser/postgresql/index.js'
export type { OperationDeparser, SchemaDeparser } from './deparser/type.js'
export { PATH_PATTERNS } from './operation/constants.js'
export {
  applyPatchOperations,
  type ChangeStatus,
  getColumnCommentChangeStatus,
  getColumnDefaultChangeStatus,
  getColumnNotNullChangeStatus,
  getColumnRelatedChangeStatus,
  getColumnTypeChangeStatus,
  getConstraintColumnNameChangeStatus,
  getConstraintColumnNamesChangeStatus,
  getConstraintDeleteConstraintChangeStatus,
  getConstraintDetailChangeStatus,
  getConstraintRelatedChangeStatus,
  getConstraintTargetColumnNameChangeStatus,
  getConstraintTargetTableNameChangeStatus,
  getConstraintUpdateConstraintChangeStatus,
  getIndexColumnsChangeStatus,
  getIndexNameChangeStatus,
  getIndexRelatedChangeStatus,
  getIndexTypeChangeStatus,
  getIndexUniqueChangeStatus,
  getOperations,
  getTableChangeStatus,
  getTableCommentChangeStatus,
  getTableRelatedChangeStatus,
  type Operation,
  operationsSchema,
} from './operation/index.js'
export type { ProcessError } from './parser.js'
export {
  aColumn,
  aForeignKeyConstraint,
  aSchema,
  aTable,
  aUniqueConstraint,
  type CheckConstraint,
  type Column,
  type Columns,
  type Constraint,
  type Constraints,
  columnSchema,
  type ForeignKeyConstraint,
  foreignKeyConstraintSchema,
  type Index,
  type Indexes,
  mergeSchemas,
  type PrimaryKeyConstraint,
  type Schema,
  schemaSchema,
  type Table,
  type Tables,
  type UniqueConstraint,
} from './schema/index.js'
export {
  type Cardinality,
  constraintsToRelationships,
  type Relationship,
  type Relationships,
} from './utils/constraintsToRelationships.js'
export { isPrimaryKey } from './utils/isPrimaryKey.js'
