export {
  postgresqlOperationDeparser,
  postgresqlSchemaDeparser,
} from './deparser/postgresql/index.js'
export type { OperationDeparser, SchemaDeparser } from './deparser/type.js'
export type {
  ChangeStatus,
  ColumnRelatedDiffItem,
  ConstraintRelatedDiffItem,
  IndexRelatedDiffItem,
  SchemaDiffItem,
  TableRelatedDiffItem,
} from './diff/index.js'
export {
  buildSchemaDiff,
  columnCommentDiffItemSchema,
  columnDefaultDiffItemSchema,
  columnDiffItemSchema,
  columnNotNullDiffItemSchema,
  columnRelatedDiffItemSchema,
  columnTypeDiffItemSchema,
  constraintColumnNameDiffItemSchema,
  constraintDeleteConstraintDiffItemSchema,
  constraintDetailDiffItemSchema,
  constraintDiffItemSchema,
  constraintNameDiffItemSchema,
  constraintRelatedDiffItemSchema,
  constraintTargetColumnNameDiffItemSchema,
  constraintTargetTableNameDiffItemSchema,
  constraintUpdateConstraintDiffItemSchema,
  getColumnChangeStatus,
  getConstraintChangeStatus,
  getIndexChangeStatus,
  getTableConstraintsChangeStatus,
  getTableIndexesChangeStatus,
  indexColumnsDiffItemSchema,
  indexDiffItemSchema,
  indexNameDiffItemSchema,
  indexRelatedDiffItemSchema,
  indexTypeDiffItemSchema,
  indexUniqueDiffItemSchema,
  schemaDiffItemsSchema,
  tableCommentDiffItemSchema,
  tableDiffItemSchema,
  tableNameDiffItemSchema,
  tableRelatedDiffItemSchema,
} from './diff/index.js'
export { PATH_PATTERNS } from './operation/constants.js'
export {
  applyPatchOperations,
  getColumnCommentChangeStatus,
  getColumnDefaultChangeStatus,
  getColumnNotNullChangeStatus,
  getColumnRelatedChangeStatus,
  getColumnTypeChangeStatus,
  getConstraintColumnNamesChangeStatus,
  getConstraintRelatedChangeStatus,
  getIndexColumnsChangeStatus,
  getIndexNameChangeStatus,
  getIndexRelatedChangeStatus,
  getIndexTypeChangeStatus,
  getIndexUniqueChangeStatus,
  getOperations,
  getTableChangeStatus,
  getTableCommentChangeStatus,
  getTableRelatedChangeStatus,
  type Operation,
  operationsSchema,
} from './operation/index.js'
export type { ProcessError } from './parser.js'
export {
  aColumn,
  aForeignKeyConstraint,
  aSchema,
  aTable,
  aUniqueConstraint,
  type CheckConstraint,
  type Column,
  type Columns,
  type Constraint,
  type Constraints,
  columnSchema,
  type ForeignKeyConstraint,
  foreignKeyConstraintSchema,
  type Index,
  type Indexes,
  mergeSchemas,
  type PrimaryKeyConstraint,
  type Schema,
  schemaSchema,
  type Table,
  type Tables,
  type UniqueConstraint,
} from './schema/index.js'
export {
  type Cardinality,
  constraintsToRelationships,
  type Relationship,
  type Relationships,
} from './utils/constraintsToRelationships.js'
export { isPrimaryKey } from './utils/isPrimaryKey.js'
