name: Add assignee to PR

on:
  pull_request:
    types: [opened]

jobs:
  add-assignee-to-pr:
    permissions:
      pull-requests: write
    uses: route06/actions/.github/workflows/add_assignee_to_pr.yml@3bcea5bf834ff2e0e6c912c1167fcc1fe05e49c2 # v2.7.0
